### ISSUE TITLE
Logo stand in?

### ISSUE THREAD

**Issue by dsmith2304** [Babywise/Restaurant-WebApp-ASP.NET#31]
Pretty sure this is a stand in. But just checking

![image](https://user-images.githubusercontent.com/78614204/233667296-cf8fda71-c194-4e86-bb45-7243ad891c1f.png)

**Comment by Babywise** [comment]
yes, i was trying to add a dummy logo, and it wasnt working so i left it in as a placeholder

**Comment by Babywise** [comment]
Image is broken on the register page of Customer
